import { valueRatio } from '../core/geometry.js';
import { m5gfxTextSize } from '../core/m5gfxText.js';

export function exportM5GfxCpp(doc) {
  const usesAnimatedSparkline = doc.elements.some((element) => element.type === 'sparkline' && element.props?.mode === 'wave');
  const lines = [
    '#include <M5Cardputer.h>',
    ...(usesAnimatedSparkline ? ['#include <math.h>'] : []),
    '',
    '// Generated by Cardputer UI Designer.',
    '// Keep bitmap/image placeholders and fonts under your own firmware assets.',
    '',
    'void drawGeneratedUi() {',
    '  auto& display = M5Cardputer.Display;',
    '  display.fillScreen(TFT_BLACK);',
    ''
  ];

  for (const element of doc.elements.filter((item) => item.visible)) {
    lines.push(...renderElement(element));
  }

  lines.push('}', '');
  return lines.join('\n');
}

function renderElement(element) {
  const out = [`  // ${element.name} (${element.type})`];
  const p = element.props;
  const fill = color(p.fill ?? '#000000');
  const stroke = color(p.stroke ?? p.color ?? '#ffffff');
  const textColor = color(p.color ?? '#ffffff');
  const radius = Math.round(p.radius ?? 0);

  if (element.type === 'rect') {
    out.push(`  display.fillRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${fill});`);
    out.push(`  display.drawRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${stroke});`);
  }

  if (element.type === 'roundRect' || element.type === 'button') {
    out.push(`  display.fillRoundRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${radius}, ${fill});`);
    out.push(`  display.drawRoundRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${radius}, ${stroke});`);
  }

  if (element.type === 'text' || element.type === 'button') {
    const datum = p.align === 'center' ? 'middle_center' : p.align === 'right' ? 'middle_right' : 'middle_left';
    const x = p.align === 'center' ? element.x + element.w / 2 : p.align === 'right' ? element.x + element.w - 3 : element.x + 3;
    out.push(`  display.setTextColor(${textColor});`);
    out.push(`  display.setTextSize(${m5gfxTextSize(p.fontSize ?? 12)});`);
    out.push(`  display.setTextDatum(${datum});`);
    out.push(`  display.drawString("${escapeCpp(p.text ?? '')}", ${n(x)}, ${n(element.y + element.h / 2)});`);
  }

  if (element.type === 'line') {
    out.push(`  display.drawLine(${n(element.x)}, ${n(element.y)}, ${n(element.x + element.w)}, ${n(element.y + element.h)}, ${stroke});`);
  }

  if (element.type === 'progress') {
    const ratio = valueRatio(p.value, p.min, p.max);
    const vertical = p.orientation === 'vertical';
    const filled = Math.max(0, Math.round(((vertical ? element.h : element.w) - 4) * ratio));
    out.push(`  display.drawRoundRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${radius}, ${stroke});`);
    if (vertical) {
      out.push(`  display.fillRoundRect(${n(element.x + 2)}, ${n(element.y + element.h - 2 - filled)}, ${n(element.w - 4)}, ${filled}, ${Math.max(0, radius - 2)}, ${fill});`);
    } else {
      out.push(`  display.fillRoundRect(${n(element.x + 2)}, ${n(element.y + 2)}, ${filled}, ${n(element.h - 4)}, ${Math.max(0, radius - 2)}, ${fill});`);
    }
  }

  if (element.type === 'gauge') {
    const cx = element.x + element.w / 2;
    const cy = element.y + element.h / 2;
    const r = Math.min(element.w, element.h) / 2 - 2;
    const ratio = valueRatio(p.value, p.min, p.max);
    const angle = -140 + ratio * 280;
    const x2 = cx + Math.cos((angle * Math.PI) / 180) * (r - 5);
    const y2 = cy + Math.sin((angle * Math.PI) / 180) * (r - 5);
    out.push(`  display.drawCircle(${n(cx)}, ${n(cy)}, ${n(r)}, ${stroke});`);
    out.push(`  display.drawLine(${n(cx)}, ${n(cy)}, ${n(x2)}, ${n(y2)}, ${fill});`);
  }

  if (element.type === 'led') {
    const r = Math.min(element.w, element.h) / 2;
    out.push(`  display.fillCircle(${n(element.x + r)}, ${n(element.y + r)}, ${n(r)}, ${fill});`);
    out.push(`  display.drawCircle(${n(element.x + r)}, ${n(element.y + r)}, ${n(r)}, ${stroke});`);
  }

  if (element.type === 'icon') {
    out.push(`  display.setTextColor(${textColor});`);
    out.push(`  display.drawString("${escapeCpp(symbolForIcon(p.icon ?? 'wifi'))}", ${n(element.x)}, ${n(element.y + element.h)});`);
  }

  if (element.type === 'sparkline') {
    if (p.fill) out.push(`  display.fillRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${fill});`);
    if (p.showAxes) {
      const axis = color(p.axis ?? '#526179');
      out.push(`  display.drawRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${axis});`);
      out.push(`  display.drawLine(${n(element.x)}, ${n(element.y + element.h / 2)}, ${n(element.x + element.w - 1)}, ${n(element.y + element.h / 2)}, ${axis});`);
      out.push(`  display.drawLine(${n(element.x + element.w / 2)}, ${n(element.y)}, ${n(element.x + element.w / 2)}, ${n(element.y + element.h - 1)}, ${axis});`);
    }
    if (p.mode === 'wave') {
      const id = safeName(element.id);
      out.push(`  const int spark_samples_${id} = ${Math.max(16, Math.min(64, Math.round(element.w / 4)))};`);
      out.push(`  const float spark_t_${id} = millis() / 1000.0f;`);
      out.push(`  int spark_prev_x_${id} = ${n(element.x)};`);
      out.push(`  int spark_prev_y_${id} = ${n(element.y + element.h / 2)};`);
      out.push(`  for (int i = 0; i < spark_samples_${id}; ++i) {`);
      out.push(`    const float x_ratio = spark_samples_${id} <= 1 ? 0.0f : (float)i / (float)(spark_samples_${id} - 1);`);
      out.push(`    const float sample = fminf(100.0f, fmaxf(0.0f, 50.0f + sinf(spark_t_${id} * 7.0f + x_ratio * 24.0f) * (22.0f + 18.0f * sinf(spark_t_${id} * 2.1f)) + sinf(spark_t_${id} * 18.0f + x_ratio * 53.0f) * 16.0f));`);
      out.push(`    const int x = ${n(element.x)} + (int)(x_ratio * ${n(element.w - 1)});`);
      out.push(`    const int y = ${n(element.y + element.h - 1)} - (int)((sample / 100.0f) * ${n(element.h - 1)});`);
      out.push(`    if (i > 0) display.drawLine(spark_prev_x_${id}, spark_prev_y_${id}, x, y, ${stroke});`);
      out.push(`    spark_prev_x_${id} = x;`);
      out.push(`    spark_prev_y_${id} = y;`);
      out.push('  }');
    } else {
      const points = p.points ?? [];
      for (let index = 0; index < points.length - 3; index += 2) {
        const x1 = element.x + (points[index] / 100) * element.w;
        const y1 = element.y + element.h - (points[index + 1] / 100) * element.h;
        const x2 = element.x + (points[index + 2] / 100) * element.w;
        const y2 = element.y + element.h - (points[index + 3] / 100) * element.h;
        out.push(`  display.drawLine(${n(x1)}, ${n(y1)}, ${n(x2)}, ${n(y2)}, ${stroke});`);
      }
    }
  }

  if (element.type === 'image') {
    out.push(`  display.drawRect(${n(element.x)}, ${n(element.y)}, ${n(element.w)}, ${n(element.h)}, ${stroke});`);
    out.push(`  // TODO: draw bitmap asset "${escapeCpp(p.imageLabel ?? 'bitmap')}" here.`);
  }

  out.push('');
  return out;
}

function color(hex) {
  const clean = hex.replace('#', '');
  if (clean.length !== 6) return 'TFT_WHITE';
  const r = parseInt(clean.slice(0, 2), 16);
  const g = parseInt(clean.slice(2, 4), 16);
  const b = parseInt(clean.slice(4, 6), 16);
  return `display.color565(${r}, ${g}, ${b})`;
}

function escapeCpp(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function n(value) {
  return Math.round(value);
}

function symbolForIcon(icon) {
  const map = { wifi: 'WiFi', sd: 'SD', battery: 'BAT', audio: 'AUD', imu: 'IMU' };
  return map[icon] ?? icon.toUpperCase();
}

function safeName(value) {
  return String(value ?? 'item').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'item';
}
