export function exportLvglC(doc) {
  const lines = [
    '#include "lvgl.h"',
    '',
    '// Generated by Cardputer UI Designer.',
    '// This is a portable LVGL skeleton. Wire fonts, styles and event callbacks in your project.',
    '',
    'void build_generated_screen(lv_obj_t* parent) {'
  ];

  doc.elements.filter((element) => element.visible).forEach((element, index) => {
    lines.push(...renderElement(element, index));
  });

  lines.push('}', '');
  return lines.join('\n');
}

function renderElement(element, index) {
  const id = `obj_${index}_${safeName(element.name)}`;
  const p = element.props;

  if (element.type === 'text') {
    return [
      `  lv_obj_t* ${id} = lv_label_create(parent);`,
      `  lv_label_set_text(${id}, "${escapeC(p.text ?? '')}");`,
      `  lv_obj_set_pos(${id}, ${Math.round(element.x)}, ${Math.round(element.y)});`,
      `  lv_obj_set_size(${id}, ${Math.round(element.w)}, ${Math.round(element.h)});`,
      ''
    ];
  }

  if (element.type === 'button') {
    return [
      `  lv_obj_t* ${id} = lv_btn_create(parent);`,
      `  lv_obj_set_pos(${id}, ${Math.round(element.x)}, ${Math.round(element.y)});`,
      `  lv_obj_set_size(${id}, ${Math.round(element.w)}, ${Math.round(element.h)});`,
      `  lv_obj_t* ${id}_label = lv_label_create(${id});`,
      `  lv_label_set_text(${id}_label, "${escapeC(p.text ?? '')}");`,
      `  lv_obj_center(${id}_label);`,
      ''
    ];
  }

  if (element.type === 'progress') {
    return [
      `  lv_obj_t* ${id} = lv_bar_create(parent);`,
      `  lv_obj_set_pos(${id}, ${Math.round(element.x)}, ${Math.round(element.y)});`,
      `  lv_obj_set_size(${id}, ${Math.round(element.w)}, ${Math.round(element.h)});`,
      `  lv_bar_set_range(${id}, ${Math.round(p.min ?? 0)}, ${Math.round(p.max ?? 100)});`,
      `  lv_bar_set_value(${id}, ${Math.round(p.value ?? 0)}, LV_ANIM_OFF);`,
      ''
    ];
  }

  if (element.type === 'gauge') {
    return [
      `  lv_obj_t* ${id} = lv_arc_create(parent);`,
      `  lv_obj_set_pos(${id}, ${Math.round(element.x)}, ${Math.round(element.y)});`,
      `  lv_obj_set_size(${id}, ${Math.round(element.w)}, ${Math.round(element.h)});`,
      `  lv_arc_set_range(${id}, ${Math.round(p.min ?? 0)}, ${Math.round(p.max ?? 100)});`,
      `  lv_arc_set_value(${id}, ${Math.round(p.value ?? 0)});`,
      ''
    ];
  }

  return [
    `  lv_obj_t* ${id} = lv_obj_create(parent);`,
    `  lv_obj_set_pos(${id}, ${Math.round(element.x)}, ${Math.round(element.y)});`,
    `  lv_obj_set_size(${id}, ${Math.round(element.w)}, ${Math.round(element.h)});`,
    `  // ${element.type}: apply custom drawing/style here.`,
    ''
  ];
}

function safeName(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'element';
}

function escapeC(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
